create table if not exists WEATHER_FACT(
    coord_id INTEGER NOT NULL,
    wahr_id TEXT NOT NULL,
    y_id TEXT NOT NULL,
    ba TEXT,
    main_mp FLOAT,
    main_fl_lik FLOAT,
    main_prur FLOAT,
    main_humidiy FLOAT,
    main_mp_min FLOAT,
    main_mp_max FLOAT,
    main_a_lvl FLOAT,
    main_grnd_lvl FLOAT,
    viibiliy FLOAT,
    wind_pd FLOAT,
    wind_dg FLOAT,
    wind_gu FLOAT,
    cloud FLOAT,
    rain_1h FLOAT,
    rain_3h FLOAT,
    snow_1h FLOAT,
    snow_3h FLOAT,
	d TEXT,
	PRIMARY KEY(coord_id,wahr_id,y_id,d),
    FOREIGN KEY(coord_id) REFERENCES GEOLOC_DIMEN(coord_id),
    FOREIGN KEY(wahr_id) REFERENCES WEATHER_DIMEN(wahr_id),
    FOREIGN KEY(y_id) REFERENCES SYS_DIMEN(y_id)
);